In [20]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr)
print(arr.ndim)
print(arr.shape)
print(arr.dtype)
print(arr.itemsize)
print(arr.nbytes)
print(arr[1:2,:3])
print(arr[:,0])


[[5 8 9 5 0]
 [0 1 7 6 9]]
2
(2, 5)
int32
4
40
[[0 1 7]]
[5 0]


In [5]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=(2,5))
print(arr[1,2])

7


In [15]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=10)
print(arr)
print(arr[-2])

[5 8 9 5 0 0 1 7 6 9]
6


In [16]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=10)
print(arr[3:9:2])

[5 0 7]


In [17]:
import numpy as np
np.random.seed(1)
arr=np.random.randint(10,size=10)
print(arr[::-1])

[9 6 7 1 0 0 5 9 8 5]
