In [3]:
import numpy as x
arr = x.array([10,20,30,40,50])
print(type(arr))

<class 'numpy.ndarray'>


In [4]:
%pip install numpy


Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.3.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [6]:
import numpy as x
arr = x.array([10,20,30,40,50])
print(type(arr))


<class 'numpy.ndarray'>


In [7]:
import numpy as x
arr = x.array([7,8,9],dtype=float)
print(type(arr),arr)

<class 'numpy.ndarray'> [7. 8. 9.]


In [13]:
import numpy as x
a= x.array([(2,3),(2,3)])
print(a)

[[2 3]
 [2 3]]


In [14]:
import numpy as x
x.empty((2,2))

array([[0.00000000e+000, 1.48287387e-311],
       [1.48287387e-311, 1.48287387e-311]])

In [17]:
import numpy as x
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [19]:
import numpy as np
np.linspace(0,1,6)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [21]:
import numpy as np
np.random.random([3,3])

array([[0.91872482, 0.72426839, 0.94639615],
       [0.42851908, 0.396343  , 0.2105995 ],
       [0.89341328, 0.56280107, 0.24514099]])